get_overdue_items:
  name: Get Overdue Items
  description: Returns a list of all components that require immediate maintenance
  fields: {}

get_due_items:
  name: Get Due Items
  description: Returns a list of all components that will need maintenance soon (within 7 days)
  fields: {}

get_all_items:
  name: Get All Items
  description: Returns a list of all components with their status
  fields: {} 