get_overdue_items:
  name: Get Overdue Items
  description: Returns a list of all components that require immediate maintenance
  fields: {}

get_due_items:
  name: Get Due Items
  description: Returns a list of all components that will need maintenance soon (within 7 days)
  fields: {}

get_all_items:
  name: Get All Items
  description: Returns a list of all components with their status
  fields: {}

set_last_maintenance:
  name: Set Last Maintenance Date
  description: Set the last maintenance date for a specific component
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the maintenance component (sensor ending with _status)
      required: true
      selector:
        entity:
          domain: sensor
    date:
      name: Maintenance Date
      description: The date when the component was last maintained
      required: true
      selector:
        date: 