perform_maintenance:
  target:
    entity:
      integration: maintainable

set_last_maintenance:
  target:
    entity:
      integration: maintainable
  fields:
    maintenance_date:
      required: true
      selector:
        date:
