name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Maintainable Integration ${{ github.ref }}
          
          ### Установка через HACS
          1. Откройте HACS
          2. Найдите "Maintainable" в интеграциях
          3. Установите и перезапустите Home Assistant
          
          ### Ручная установка
          1. Скачайте исходный код
          2. Скопируйте `custom_components/maintainable` в папку `custom_components` вашего Home Assistant
          3. Перезапустите Home Assistant
          
          ### Новое в этой версии
          - Отслеживание компонентов обслуживания
          - Автоматические статусы и уведомления
          - Кнопки для быстрого обслуживания
          - Русская локализация
        draft: false
        prerelease: false 